// Generated by CoffeeScript 1.6.3
(function() {
  var path, transformTools;

  path = require('path');

  transformTools = require('browserify-transform-tools');

  module.exports = transformTools.makeRequireTransform("aliasify", function(args, opts, cb) {
    var config, fileDir, relative, replacement;
    config = opts.config;
    if (args.length > 0 && (config[args[0]] != null)) {
      replacement = config[args[0]];
      replacement = path.resolve(opts.configDir, replacement);
      fileDir = path.dirname(opts.file);
      relative = path.relative(fileDir, replacement);
      return cb(null, "require('" + relative + "')");
    } else {
      return cb();
    }
  });

}).call(this);
