// Generated by CoffeeScript 1.6.3
(function() {
  var path, transformTools;

  path = require('path');

  transformTools = require('browserify-transform-tools');

  module.exports = transformTools.makeRequireTransform("aliasify", function(args, opts, cb) {
    var aliases, fileDir, relative, replacement, verbose, _ref, _ref1;
    aliases = (_ref = opts.config) != null ? _ref.aliases : void 0;
    verbose = (_ref1 = opts.config) != null ? _ref1.verbose : void 0;
    if ((args.length > 0) && (aliases != null) && (aliases[args[0]] != null)) {
      replacement = aliases[args[0]];
      replacement = path.resolve(opts.configData.configDir, replacement);
      fileDir = path.dirname(opts.file);
      relative = "./" + (path.relative(fileDir, replacement));
      if (verbose) {
        console.log("aliasify - " + opts.file + ": replacing " + args[0] + " with " + relative);
      }
      return cb(null, "require('" + relative + "')");
    } else {
      return cb();
    }
  });

}).call(this);
